### ISSUE TITLE
Dependencies Missing From Package File

### ISSUE THREAD

**Issue by merktassel** [MKS-Elixr/jubilant-umbrella#15]
It seems like someone might've ran `npm install body-parser` (and others) without `--save`.

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'body-parser'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/markcastle/Documents/Side Projects/jubilant-umbrella/server/server.js:2:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

To replicate this issue, remove the `node_modules` directory in `server` and run `npm install && node server.js`.

**Comment by merktassel** [comment]
It looks like there's still at least one missing dependency (CORS).
