### ISSUE TITLE
Server Crashes on Movement

### ISSUE THREAD

**Issue by merktassel** [MKS-Elixr/jubilant-umbrella#85]
```
2016-05-18T04:18:24.884184+00:00 app[web.1]: New Connection
2016-05-18T04:18:30.879669+00:00 app[web.1]: New Connection
2016-05-18T04:18:36.870405+00:00 app[web.1]: New Connection
2016-05-18T04:18:43.854833+00:00 app[web.1]: New Connection
2016-05-18T04:18:49.868718+00:00 app[web.1]: New Connection
2016-05-18T04:18:56.277892+00:00 app[web.1]: New Connection
2016-05-18T04:19:01.869059+00:00 app[web.1]: New Connection
2016-05-18T04:24:39.384902+00:00 app[web.1]: New Connection
2016-05-18T04:24:52.068336+00:00 app[web.1]: Button Pressed { email: 'testdain@email.com',
2016-05-18T04:24:52.068345+00:00 app[web.1]:   location: { latitude: 34.0193646122087, longitude: -118.4943332244814 } }
2016-05-18T04:24:52.085681+00:00 app[web.1]: studentid 1
2016-05-18T04:24:52.085704+00:00 app[web.1]: schoolid 1
2016-05-18T04:24:52.085730+00:00 app[web.1]: chain continued
2016-05-18T04:24:52.085768+00:00 app[web.1]: inside event
2016-05-18T04:24:52.104671+00:00 app[web.1]: event inserted  [ 1114 ]
2016-05-18T04:24:52.104782+00:00 app[web.1]: inside insertevent [ 1114 ]
2016-05-18T04:24:52.104854+00:00 app[web.1]: eventid [ 1114 ]
2016-05-18T04:24:52.104894+00:00 app[web.1]: chain continued 2
2016-05-18T04:24:52.153991+00:00 app[web.1]: this is resp from insertstudentsevents [ 1162 ]
2016-05-18T04:24:52.154069+00:00 app[web.1]: studentevent inserted [ 1162 ]
2016-05-18T04:24:52.154116+00:00 app[web.1]: chain continued 2.5
2016-05-18T04:24:52.154149+00:00 app[web.1]: this is location server.js [{"latitude":34.0193646122087,"longitude":-118.4943332244814,"timestamp":"Wed, 18 May 2016 04:24:52 GMT"}]
2016-05-18T04:24:52.154173+00:00 app[web.1]: trigered
2016-05-18T04:24:52.172904+00:00 app[web.1]: initial location inserted [ 1165 ]
2016-05-18T04:24:52.173007+00:00 app[web.1]: chain continued 3
2016-05-18T04:24:52.191850+00:00 app[web.1]: this is response [ { id: 'X9K68',
2016-05-18T04:24:52.191870+00:00 app[web.1]:     by: 'dain',
2016-05-18T04:24:52.191872+00:00 app[web.1]:     started: Wed May 18 2016 00:24:52 GMT+0000 (UTC),
2016-05-18T04:24:52.191871+00:00 app[web.1]:     phone: 123,
2016-05-18T04:24:52.191873+00:00 app[web.1]:     active: true,
2016-05-18T04:24:52.191873+00:00 app[web.1]:     location: 
2016-05-18T04:24:52.191874+00:00 app[web.1]:      { latitude: 34.0193646122087,
2016-05-18T04:24:52.191874+00:00 app[web.1]:        longitude: -118.4943332244814,
2016-05-18T04:24:52.191875+00:00 app[web.1]:        timestamp: 'Wed, 18 May 2016 04:24:52 GMT' },
2016-05-18T04:24:52.191875+00:00 app[web.1]:     ended: null } ]
2016-05-18T04:24:52.332143+00:00 app[web.1]: Button Pressed { email: 'testdain@email.com',
2016-05-18T04:24:52.332152+00:00 app[web.1]:   location: { latitude: 34.01936441825874, longitude: -118.4943333485285 } }
2016-05-18T04:24:52.349538+00:00 app[web.1]: studentid 1
2016-05-18T04:24:52.349553+00:00 app[web.1]: schoolid 1
2016-05-18T04:24:52.349627+00:00 app[web.1]: chain continued
2016-05-18T04:24:52.349630+00:00 app[web.1]: inside event
2016-05-18T04:24:52.373018+00:00 app[web.1]: event inserted  [ 1117 ]
2016-05-18T04:24:52.373106+00:00 app[web.1]: inside insertevent [ 1117 ]
2016-05-18T04:24:52.373189+00:00 app[web.1]: eventid [ 1117 ]
2016-05-18T04:24:52.373214+00:00 app[web.1]: chain continued 2
2016-05-18T04:24:52.406934+00:00 app[web.1]: this is resp from insertstudentsevents [ 1165 ]
2016-05-18T04:24:52.407030+00:00 app[web.1]: studentevent inserted [ 1165 ]
2016-05-18T04:24:52.407075+00:00 app[web.1]: chain continued 2.5
2016-05-18T04:24:52.407107+00:00 app[web.1]: this is location server.js [{"latitude":34.01936441825874,"longitude":-118.4943333485285,"timestamp":"Wed, 18 May 2016 04:24:52 GMT"}]
2016-05-18T04:24:52.407172+00:00 app[web.1]: trigered
2016-05-18T04:24:52.425264+00:00 app[web.1]: initial location inserted [ 1168 ]
2016-05-18T04:24:52.425281+00:00 app[web.1]: chain continued 3
2016-05-18T04:24:52.442675+00:00 app[web.1]: this is response [ { id: 'LPYSU',
2016-05-18T04:24:52.442693+00:00 app[web.1]:     by: 'dain',
2016-05-18T04:24:52.442694+00:00 app[web.1]:     phone: 123,
2016-05-18T04:24:52.442695+00:00 app[web.1]:     started: Wed May 18 2016 00:24:52 GMT+0000 (UTC),
2016-05-18T04:24:52.442696+00:00 app[web.1]:     active: true,
2016-05-18T04:24:52.442697+00:00 app[web.1]:     location: 
2016-05-18T04:24:52.442697+00:00 app[web.1]:      { latitude: 34.01936441825874,
2016-05-18T04:24:52.442698+00:00 app[web.1]:        longitude: -118.4943333485285,
2016-05-18T04:24:52.442699+00:00 app[web.1]:        timestamp: 'Wed, 18 May 2016 04:24:52 GMT' },
2016-05-18T04:24:52.442699+00:00 app[web.1]:     ended: null } ]
2016-05-18T04:24:52.516107+00:00 app[web.1]: Movement Detected { id: 'X9K68',
2016-05-18T04:24:52.516125+00:00 app[web.1]:   latitude: 34.01935385258971,
2016-05-18T04:24:52.516126+00:00 app[web.1]:   longitude: -118.4943409394998 }
2016-05-18T04:24:52.516319+00:00 app[web.1]: Missing error handler on `socket`.
2016-05-18T04:24:52.516709+00:00 app[web.1]: TypeError: Cannot set property 'timestamp' of undefined
2016-05-18T04:24:52.516724+00:00 app[web.1]:     at Socket.<anonymous> (/app/server.js:104:32)
2016-05-18T04:24:52.516725+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-05-18T04:24:52.516725+00:00 app[web.1]:     at Socket.emit (events.js:182:7)
2016-05-18T04:24:52.516726+00:00 app[web.1]:     at Socket.onevent (/app/node_modules/socket.io/lib/socket.js:335:8)
2016-05-18T04:24:52.516727+00:00 app[web.1]:     at Socket.onpacket (/app/node_modules/socket.io/lib/socket.js:295:12)
2016-05-18T04:24:52.516728+00:00 app[web.1]:     at Client.ondecoded (/app/node_modules/socket.io/lib/client.js:193:14)
2016-05-18T04:24:52.516729+00:00 app[web.1]:     at Decoder.add (/app/node_modules/socket.io-parser/index.js:247:12)
2016-05-18T04:24:52.516729+00:00 app[web.1]:     at Decoder.Emitter.emit (/app/node_modules/component-emitter/index.js:134:20)
2016-05-18T04:24:52.516730+00:00 app[web.1]:     at Client.ondata (/app/node_modules/socket.io/lib/client.js:175:18)
2016-05-18T04:24:52.516731+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-05-18T04:24:52.516732+00:00 app[web.1]:     at Socket.onPacket (/app/node_modules/engine.io/lib/socket.js:101:14)
2016-05-18T04:24:52.516732+00:00 app[web.1]:     at Socket.emit (events.js:182:7)
2016-05-18T04:24:52.516733+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-05-18T04:24:52.516734+00:00 app[web.1]:     at WebSocket.Transport.onPacket (/app/node_modules/engine.io/lib/transport.js:104:8)
2016-05-18T04:24:52.516735+00:00 app[web.1]:     at WebSocket.Transport.onData (/app/node_modules/engine.io/lib/transport.js:115:8)
2016-05-18T04:24:52.516734+00:00 app[web.1]:     at WebSocket.emit (events.js:182:7)
2016-05-18T04:24:52.516737+00:00 app[web.1]:     at emitTwo (events.js:100:13)
2016-05-18T04:24:52.516737+00:00 app[web.1]:     at WebSocket.emit (events.js:185:7)
2016-05-18T04:24:52.516738+00:00 app[web.1]:     at Receiver.ontext (/app/node_modules/ws/lib/WebSocket.js:816:10)
2016-05-18T04:24:52.516736+00:00 app[web.1]:     at WebSocket.onData (/app/node_modules/engine.io/lib/transports/websocket.js:76:30)
2016-05-18T04:24:52.516739+00:00 app[web.1]:     at /app/node_modules/ws/lib/Receiver.js:477:18
2016-05-18T04:24:52.516739+00:00 app[web.1]:     at Receiver.applyExtensions (/app/node_modules/ws/lib/Receiver.js:364:5)
```

**Comment by merktassel** [comment]
The latest round of errors:

```
2016-05-19T02:05:24.542361+00:00 app[web.1]:     at tryOnImmediate (timers.js:534:15)
2016-05-19T02:05:24.392089+00:00 app[web.1]:   timestamp: 'Thu, 19 May 2016 02:05:24 GMT' }
2016-05-19T02:05:24.409599+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
2016-05-19T02:05:24.506096+00:00 app[web.1]:   timestamp: 'Thu, 19 May 2016 02:05:24 GMT' }
2016-05-19T02:05:24.507612+00:00 app[web.1]:   timestamp: 'Thu, 19 May 2016 02:05:24 GMT' }
2016-05-19T02:05:24.409584+00:00 app[web.1]: Unhandled rejection TypeError: Cannot read property 'ID' of undefined
2016-05-19T02:05:24.409595+00:00 app[web.1]:     at /app/routes/sockethelper.js:118:50
2016-05-19T02:05:24.409596+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
2016-05-19T02:05:24.507610+00:00 app[web.1]: this is the new data.location { latitude: 34.01936880316028,
2016-05-19T02:05:24.526883+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
2016-05-19T02:05:24.409597+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
2016-05-19T02:05:24.409597+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
2016-05-19T02:05:24.409598+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
2016-05-19T02:05:24.409599+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
2016-05-19T02:05:24.409602+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
2016-05-19T02:05:24.506095+00:00 app[web.1]:   longitude: -118.4943825100721,
2016-05-19T02:05:24.506728+00:00 app[web.1]:   timestamp: 'Thu, 19 May 2016 02:05:24 GMT' }
2016-05-19T02:05:24.525667+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
2016-05-19T02:05:24.526862+00:00 app[web.1]: Unhandled rejection TypeError: Cannot read property 'ID' of undefined
2016-05-19T02:05:24.526888+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:514:5)
2016-05-19T02:05:24.542359+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
2016-05-19T02:05:24.391986+00:00 app[web.1]: Movement Detected { id: 'BM39G',
2016-05-19T02:05:24.409603+00:00 app[web.1]:     at tryOnImmediate (timers.js:534:15)
2016-05-19T02:05:24.507612+00:00 app[web.1]:   longitude: -118.4943825100721,
2016-05-19T02:05:24.525668+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
2016-05-19T02:05:24.525671+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
2016-05-19T02:05:24.526887+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
2016-05-19T02:05:24.392004+00:00 app[web.1]:   location: { latitude: 34.01936880316028, longitude: -118.4943825100721 } }
2016-05-19T02:05:24.506094+00:00 app[web.1]: this is the new data.location { latitude: 34.01936880316028,
2016-05-19T02:05:24.506586+00:00 app[web.1]:   location: { latitude: 34.01936880316028, longitude: -118.4943825100721 } }
2016-05-19T02:05:24.525668+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
2016-05-19T02:05:24.526884+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
2016-05-19T02:05:24.542359+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
2016-05-19T02:05:24.525669+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
2016-05-19T02:05:24.526882+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
2016-05-19T02:05:24.542357+00:00 app[web.1]:     at /app/routes/sockethelper.js:118:50
2016-05-19T02:05:24.542362+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:514:5)
2016-05-19T02:05:24.525672+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:514:5)
2016-05-19T02:05:24.526885+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
2016-05-19T02:05:24.542360+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
2016-05-19T02:05:24.542358+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
2016-05-19T02:05:24.807374+00:00 app[web.1]: Button Pressed { email: 'testdain@email.com',
2016-05-19T02:05:24.873933+00:00 app[web.1]: this is resp from insertstudentsevents [ 172 ]
2016-05-19T02:05:24.907529+00:00 app[web.1]:     by: 'dain',
2016-05-19T02:05:25.003913+00:00 app[web.1]:   longitude: -118.4943825100721,
2016-05-19T02:05:25.003914+00:00 app[web.1]:   timestamp: 'Thu, 19 May 2016 02:05:25 GMT' }
2016-05-19T02:05:25.010909+00:00 app[web.1]: Movement Detected { id: 'AT5HS',
2016-05-19T02:05:25.027900+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
2016-05-19T02:05:24.807385+00:00 app[web.1]:   location: { latitude: 34.01936880316028, longitude: -118.4943825100721 } }
2016-05-19T02:05:24.873952+00:00 app[web.1]: studentevent inserted [ 172 ]
2016-05-19T02:05:24.907530+00:00 app[web.1]:     started: Wed May 18 2016 22:05:24 GMT+0000 (UTC),
2016-05-19T02:05:24.907531+00:00 app[web.1]:     active: true,
2016-05-19T02:05:25.011051+00:00 app[web.1]:   longitude: -118.4943825100721,
2016-05-19T02:05:25.019880+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
2016-05-19T02:05:24.824825+00:00 app[web.1]: chain continued
2016-05-19T02:05:24.873994+00:00 app[web.1]: chain continued 2.5
2016-05-19T02:05:24.907530+00:00 app[web.1]:     phone: 123,
2016-05-19T02:05:25.003778+00:00 app[web.1]: Movement Detected { id: 'AT5HS',
2016-05-19T02:05:25.019878+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
2016-05-19T02:05:25.027902+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
2016-05-19T02:05:24.824842+00:00 app[web.1]: inside event
2016-05-19T02:05:24.873996+00:00 app[web.1]: this is location server.js [{"latitude":34.01936880316028,"longitude":-118.4943825100721,"timestamp":"Thu, 19 May 2016 02:05:24 GMT"}]
2016-05-19T02:05:25.003790+00:00 app[web.1]:   location: { latitude: 34.01936880316028, longitude: -118.4943825100721 } }
2016-05-19T02:05:25.019879+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
2016-05-19T02:05:25.027906+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:514:5)
2016-05-19T02:05:24.841013+00:00 app[web.1]: event inserted  [ 169 ]
2016-05-19T02:05:24.874039+00:00 app[web.1]: trigered
2016-05-19T02:05:25.010918+00:00 app[web.1]:   location: { latitude: 34.01936880316028, longitude: -118.4943825100721 } }
2016-05-19T02:05:24.824531+00:00 app[web.1]: schoolid 1
2016-05-19T02:05:24.890621+00:00 app[web.1]: initial location inserted [ 172 ]
2016-05-19T02:05:24.907532+00:00 app[web.1]:     location: 
2016-05-19T02:05:24.907532+00:00 app[web.1]:      { latitude: 34.01936880316028,
2016-05-19T02:05:24.907532+00:00 app[web.1]:        longitude: -118.4943825100721,
2016-05-19T02:05:25.027899+00:00 app[web.1]:     at /app/routes/sockethelper.js:118:50
2016-05-19T02:05:24.824508+00:00 app[web.1]: studentid 1
2016-05-19T02:05:25.003911+00:00 app[web.1]: this is the new data.location { latitude: 34.01936880316028,
2016-05-19T02:05:25.019881+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
2016-05-19T02:05:24.841322+00:00 app[web.1]: chain continued 2
2016-05-19T02:05:24.890654+00:00 app[web.1]: chain continued 3
2016-05-19T02:05:24.907533+00:00 app[web.1]:     ended: null } ]
2016-05-19T02:05:25.019878+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
2016-05-19T02:05:25.027900+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
2016-05-19T02:05:24.841273+00:00 app[web.1]: eventid [ 169 ]
2016-05-19T02:05:24.907508+00:00 app[web.1]: this is response [ { id: 'AT5HS',
2016-05-19T02:05:25.011049+00:00 app[web.1]: this is the new data.location { latitude: 34.01936880316028,
2016-05-19T02:05:25.027904+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
2016-05-19T02:05:25.027905+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
2016-05-19T02:05:25.027905+00:00 app[web.1]:     at tryOnImmediate (timers.js:534:15)
2016-05-19T02:05:24.841177+00:00 app[web.1]: inside insertevent [ 169 ]
2016-05-19T02:05:24.907533+00:00 app[web.1]:        timestamp: 'Thu, 19 May 2016 02:05:24 GMT' },
2016-05-19T02:05:25.011052+00:00 app[web.1]:   timestamp: 'Thu, 19 May 2016 02:05:25 GMT' }
2016-05-19T02:05:25.019860+00:00 app[web.1]: Unhandled rejection TypeError: Cannot read property 'ID' of undefined
2016-05-19T02:05:25.019875+00:00 app[web.1]:     at /app/routes/sockethelper.js:118:50
2016-05-19T02:05:25.019876+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
2016-05-19T02:05:25.019877+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
2016-05-19T02:05:25.019881+00:00 app[web.1]:     at tryOnImmediate (timers.js:534:15)
2016-05-19T02:05:25.019882+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:514:5)
2016-05-19T02:05:25.027891+00:00 app[web.1]: Unhandled rejection TypeError: Cannot read property 'ID' of undefined
2016-05-19T02:05:25.027903+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
2016-05-19T02:05:25.027902+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
```
